### ISSUE TITLE
Build Failed Issues

### ISSUE THREAD

**Issue by Nik20112** [iamvucms/react-native-instagram-clone#35]
Please help on below issues.

Facing below errors while execute **yarn** command.

`../../nan/nan_callbacks_12_inl.h:89:22: warning: unused parameter 'whatever' [-Wunused-parameter]
  inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
                     ^
In file included from ../ext/byte_buffer.cc:21:
../../nan/nan.h:1796:44: warning: unused parameter 'isolate' [-Wunused-parameter]
  MaybeLocal<v8::Value> Call_(v8::Isolate *isolate
                                           ^
../../nan/nan.h:2212:19: warning: unused parameter 'resource_name' [-Wunused-parameter]
      const char* resource_name = "nan:AsyncProgressQueueWorker")
                  ^
../../nan/nan.h:2536:8: error: no matching member function for call to 'SetAccessor'
  tpl->SetAccessor(
  ~~~~~^~~~~~~~~~~
/Users/nikunjjadav/Library/Caches/node-gyp/19.0.1/include/node/v8-template.h:814:8: note: candidate function not viable: no known conversion from 'imp::Sig' (aka 'int') to 'v8::SideEffectType' for 7th argument
  void SetAccessor(
       ^
/Users/nikunjjadav/Library/Caches/node-gyp/19.0.1/include/node/v8-template.h:807:8: note: candidate function not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'v8::AccessorGetterCallback' (aka 'void (*)(Local<v8::String>, const PropertyCallbackInfo<v8::Value> &)') for 2nd argument
  void SetAccessor(
       ^
In file included from ../ext/byte_buffer.cc:21:
In file included from ../../nan/nan.h:2884:
../../nan/nan_typedarray_contents.h:34:43: error: no member named 'GetContents' in 'v8::ArrayBuffer'
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                  ~~~~~~~~^
../ext/byte_buffer.cc:51:26: warning: unused parameter 'data' [-Wunused-parameter]
void delete_buffer(char *data, void *hint) {
                         ^
88 warnings and 7 errors generated.
make: *** [Release/obj.target/grpc_node/ext/byte_buffer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/homebrew/Cellar/node/19.0.1/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/opt/homebrew/Cellar/node/19.0.1/bin/node" "/opt/homebrew/Cellar/node/19.0.1/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/Users/nikunjjadav/Documents/ClientApps/ReactNative-Demo/react-native-instagram-clone/node_modules/grpc/src/node/extension_binary/node-v111-darwin-arm64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/nikunjjadav/Documents/ClientApps/ReactNative-Demo/react-native-instagram-clone/node_modules/grpc/src/node/extension_binary/node-v111-darwin-arm64-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v111"
gyp ERR! cwd /Users/nikunjjadav/Documents/ClientApps/ReactNative-Demo/react-native-instagram-clone/node_modules/grpc
gyp ERR! node -v v19.0.1
**gyp ERR! node-gyp -v v9.1.0**
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --library=static_library --module=/Users/nikunjjadav/Documents/ClientApps/ReactNative-Demo/react-native-instagram-clone/node_modules/grpc/src/node/extension_binary/node-v111-darwin-arm64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/nikunjjadav/Documents/ClientApps/ReactNative-Demo/react-native-instagram-clone/node_modules/grpc/src/node/extension_binary/node-v111-darwin-arm64-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v111' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/nikunjjadav/Documents/ClientApps/ReactNative-Demo/react-native-instagram-clone/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
node-pre-gyp ERR! System Darwin 21.6.0
node-pre-gyp ERR! command "/opt/homebrew/Cellar/node/19.0.1/bin/node" "/Users/nikunjjadav/Documents/ClientApps/ReactNative-Demo/react-native-instagram-clone/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/nikunjjadav/Documents/ClientApps/ReactNative-Demo/react-native-instagram-clone/node_modules/grpc
node-pre-gyp ERR! node -v v19.0.1
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok 
**Failed to execute 'node-gyp build --fallback-to-build --library=static_library --module=/Users/nikunjjadav/Documents/ClientApps/ReactNative-D`**

**Comment by Alex-Cook4** [comment]
Did you have any luck figuring out how to get it to build? I would really love to try it out.
